---
- name: reboot vm
  shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server
  local_action: wait_for port=22 host={{ ansible_host | default(inventory_hostname) }} state=started delay=10 timeout=600 connect_timeout=10
  become: no
