---
- name: Setup deps repo for mock
  get_url:
    url: https://trunk.rdoproject.org/centos8-master/delorean-deps.repo
    dest: /etc/yum.repos.d/delorean-deps.repo
  become: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == '8'

- name: Install pre-requisites for mock
  package:
    name:
      - createrepo
      - mock
      - redhat-rpm-config
      - rpmdevtools
      - spectool
      - gcc
      - httpd
      - libffi-devel
      - openssl-devel
      - python3-pip
    state: present
  become: true

- name: Remove deps repo
  file:
    path: /etc/yum.repos.d/delorean-deps.repo
    state: absent
  become: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == '8'

- name: Ensure user in mock group
  user:
    name: "{{ ansible_user }}"
    groups: mock
    append: true
  become: true

- name: clone DLRN repo
  git:
    repo: https://github.com/softwarefactory-project/DLRN.git
    dest: "/home/{{ ansible_user }}/workspace/dlrn"
  become: "{{ ansible_user }}"

- name: install requirements
  pip:
    requirements: "/home/{{ ansible_user }}/workspace/dlrn/requirements.txt"

- name: install dlrn
  command: python3 setup.py develop
  args:
    chdir: "/home/{{ ansible_user }}/workspace/dlrn"
