---
- name: fetch CRC binary
  shell:
    cmd: |
      curl -LO https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
      tar xvf crc-linux-amd64.tar.xz
      cp ~/crc-linux-*-amd64/crc /usr/local/bin
  changed_when: true

- name: setup CRC with OKD
  shell:
    cmd: |
      crc config set preset okd
      crc config set consent-telemetry yes
      crc config view
      crc setup
  changed_when: true

- name: start OKD
  shell:
    cmd: |
      crc start
  changed_when: true
